#%RAML 1.0 Library

types :
  StatusType :
    type : string
    enum : [
      OK, 
      ERROR, 
      INVALIDE_ARGUMENT,  
      PLAYERS_NO_FOUND, 
      NAME_PLAYER_NOT_AVAILABLE, 
      NAME_GAME_NOT_AVAILABLE,
      BUSY_IA
    ]